# Generated by Django 4.2.11 on 2026-07-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_deleted_at_product_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
    ]
